const{test}=require('node:test'),assert=require('node:assert/strict');const{createHandler}=require('../lib/demo-handler');
const env={SMTP_HOST:'smtp.example.org',SMTP_PORT:'465',SMTP_USER:'test@example.org',SMTP_PASS:'test-only',SMTP_FROM:'test@example.org',SMTP_TO:'team@example.org',SITE_URL:'https://example.org'};
const valid={prenom:'Awa',nom:'Démo',email:'awa@example.org',org:'Organisation démo',consent:true,role:'DPO',message:'Bonjour',website:''};
function response(){return{headers:{},setHeader(k,v){this.headers[k]=v},status(s){this.code=s;return this},json(o){this.body=o;return this}}}
function request(body=valid,options={}){return{method:'POST',headers:{'content-type':'application/json',origin:'https://example.org','x-forwarded-for':'127.0.0.1'},body,...options}}
function setup(overrides={}){const mails=[],configs=[];const handler=createHandler({env,logger:{error(){}},createTransport(config){configs.push(config);return{sendMail:async mail=>{mails.push(mail);return{accepted:['team@example.org']}},close(){}}},...overrides});return{handler,mails,configs}}
test('valid request sends one escaped email to configured recipient',async()=>{const{handler,mails,configs}=setup();const r=response();await handler(request({...valid,org:'<img src=x onerror=alert(1)>',message:'<script>test</script>'}),r);assert.equal(r.code,200);assert.equal(mails.length,1);assert.deepEqual(mails[0].to,['team@example.org']);assert.equal(mails[0].replyTo,valid.email);assert(!mails[0].html.includes('<script>'));assert(mails[0].html.includes('&lt;script&gt;'));assert.equal(configs[0].tls.rejectUnauthorized,true);assert.equal(configs[0].secure,true)});
test('missing required field rejected',async()=>{const{handler,mails}=setup();const r=response();await handler(request({...valid,org:''}),r);assert.equal(r.code,400);assert.equal(mails.length,0)});
test('consent required',async()=>{const{handler}=setup();const r=response();await handler(request({...valid,consent:false}),r);assert.equal(r.code,400)});
test('invalid email and header injection rejected',async()=>{const{handler}=setup();for(const body of[{...valid,email:'invalid'},{...valid,org:'Name\r\nBcc: victim@example.org'}]){const r=response();await handler(request(body),r);assert.equal(r.code,400)}});
test('overlong and wrong-type fields rejected',async()=>{const{handler}=setup();for(const body of[{...valid,message:'x'.repeat(2001)},{...valid,nom:{value:'demo'}}]){const r=response();await handler(request(body),r);assert.equal(r.code,400)}});
test('method, content type, origin rejected',async()=>{const{handler}=setup();for(const[opts,status]of[[{method:'GET'},405],[{headers:{'content-type':'text/plain'}},415],[{headers:{'content-type':'application/json',origin:'https://attacker.example'}},403]]){const r=response();await handler(request(valid,opts),r);assert.equal(r.code,status)}});
test('malformed body rejected',async()=>{const{handler}=setup();for(const body of['{',null,[]]){const r=response();await handler(request(body),r);assert.equal(r.code,400)}});
test('honeypot does not send',async()=>{const{handler,mails}=setup();const r=response();await handler(request({...valid,website:'spam'}),r);assert.equal(r.code,200);assert.equal(mails.length,0)});
test('unconfigured server never claims delivery',async()=>{const{handler,mails}=setup({env:{SITE_URL:'https://example.org'}});const r=response();await handler(request(),r);assert.equal(r.code,503);assert.equal(r.body.ok,false);assert.equal(mails.length,0)});
test('SMTP failure gives error without leaking credentials',async()=>{const{handler}=setup({createTransport:()=>({sendMail:async()=>{throw Object.assign(Error('private info'),{code:'EAUTH'})}})});const r=response();await handler(request(),r);assert.equal(r.code,502);assert(!JSON.stringify(r.body).includes('private info'))});
test('no accepted recipient is not success',async()=>{const{handler}=setup({createTransport:()=>({sendMail:async()=>({accepted:[]})})});const r=response();await handler(request(),r);assert.equal(r.code,502)});
test('rate limit and reset',async()=>{let timestamp=1000;const{handler}=setup({now:()=>timestamp});for(let i=0;i<5;i++){const r=response();await handler(request(),r);assert.equal(r.code,200)}const blocked=response();await handler(request(),blocked);assert.equal(blocked.code,429);timestamp+=61000;const next=response();await handler(request(),next);assert.equal(next.code,200)});
test('587 enforces STARTTLS',async()=>{const{handler,configs}=setup({env:{...env,SMTP_PORT:'587'}});await handler(request(),response());assert.equal(configs[0].secure,false);assert.equal(configs[0].requireTLS,true)});
